### ISSUE TITLE
Invalid 4.2 URLs for Release Notes and Changelog (APIM & AM)

### ISSUE THREAD

**Issue by lfavreli** [gravitee-io/gravitee-platform-docs#132]
Hello Gravitee Team,

Since the publication of v4.3 documentation, the Release Notes and Changelog links for API Management and Access Management in version 4.2 are KO.

**API Management**:

1. Release Notes

- Deployed (KO) : `/apim/releases-and-changelog/release-notes/apim-4.2`
- Should be replaced by : `/apim/v/4.2/releases-and-changelog/release-notes/apim-4.2`

2. Changelog

- Deployed (KO) : `/apim/releases-and-changelog/changelog/apim-4.2.x`
- Should be replaced by : `/apim/v/4.2/releases-and-changelog/changelog/apim-4.2.x`

**Access Management**:

1. Release Notes

- Deployed (KO) : `/am/releases-and-changelog/release-notes/am-4.2`
- Should be replaced by : `/am/v/4.2-1/releases-and-changelog/release-notes/am-4.2`

2. Changelog

- Deployed (KO) : `/am/releases-and-changelog/changelogs/am-4.2.x-changelog`
- Should be replaced by : `/am/v/4.2-1/releases-and-changelog/changelogs/am-4.2.x-changelog`

---

Thank you in advance for your consideration.
Hope it helps! 🙏

**Comment by Lyd1aCla1r3** [comment]
@lfavreli fixed! Thank you so much for the catch :)

**Comment by Lyd1aCla1r3** [comment]
4.2 APIM/AM release notes / changelog links updated to reflect new URLs
