### ISSUE TITLE
Missing "Repositories" page on documentation

### ISSUE THREAD

**Issue by ssensini** [gravitee-io/gravitee-platform-docs#20]
Hi!

On [this](https://documentation.gravitee.io/apim/overview/plugins#repositories) page there's a section dedicated to Repositories and there's a missing reference that could be instead very helpful:

![immagine](https://github.com/gravitee-io/gravitee-platform-docs/assets/99977081/a29e661d-b913-4f5c-a29f-6b1db72a0af6)

This is the [referred](https://github.com/gravitee-io/gravitee-platform-docs/blob/main/docs/apim/overview/introduction-to-gravitee-api-management-apim/broken-reference/README.md) link.

**Comment by bigmike36c** [comment]
Thanks for reporting this! I've updated the link to point to the correct page.
